#!/bin/bash
set -e

# The Jenkins Docker image creates an env variable VENV_ACTIVATE
# This allows runtests to be run locally, if a venv is activated.
if [[ -z "${VIRTUAL_ENV}" ]]; then
    . $VENV_ACTIVATE
fi

: ${OUTPUT_DIR:="."}

make clean

# Run the test suite with checks and assertions
SANITIZE_ADDRESS=1 SANITIZE_UNDEFINED=1 make test

echo $OUTPUT_DIR/libpy_report.xml
# Run tests with a release build
GTEST_OUTPUT="xml:$OUTPUT_DIR/libpy_report.xml" make test
