#!/bin/bash
set -e

: ${OUTPUT_DIR:="."}

make clean

# Run the test suite with checks and assertions
SANITIZE_ADDRESS=1 SANITIZE_UNDEFINED=1 make test

# Run tests with a release build
GTEST_OUTPUT="xml:$OUTPUT_DIR/libpy_report.xml" make test
